# Generated by Django 3.2.4 on 2021-06-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
